import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {plan} from './preflight.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mail-preflight-test-'));
const entries=Array.from({length:8},(_,i)=>{const p=path.join(dir,`测试${i}.docx`);fs.writeFileSync(p,Buffer.alloc(30000,i));return {path:p};});
const r=plan(entries);
assert.deepEqual(r.batches.map(b=>b.attachments.length),[4,4]);
assert.ok(r.batches.every(b=>b.request_bytes<=180000));
assert.equal(r.batches.flatMap(b=>b.attachments).length,8);
assert.equal(plan(entries.slice(0,1)).batches.length,1);
assert.throws(()=>plan([{...entries[0],sha256:'wrong'}]),/File changed/);
assert.throws(()=>plan([entries[0],entries[0]]),/Duplicate/);
assert.throws(()=>plan([{path:path.join(dir,'missing.docx')}]),/ENOENT/);
assert.throws(()=>plan(entries,{budget:1000}),/SINGLE_ATTACHMENT_OVER_BUDGET/);
assert.throws(()=>plan([]),/No attachments/);
assert.throws(()=>plan([{path:'relative.docx'}]),/absolute/);
const zero=path.join(dir,'empty.docx');fs.writeFileSync(zero,'');
assert.throws(()=>plan([{path:zero}]),/Empty/);
const unknown=path.join(dir,'unknown.bin');fs.writeFileSync(unknown,'x');
assert.throws(()=>plan([{path:unknown}]),/Unknown MIME/);
console.log(JSON.stringify({result:'PASS',checks:11,network_calls:0,emails_sent:0,temp_fixtures:dir}));
